server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgresql
    source: postgresql://postgres:123456@localhost:5433/resource
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbitmq:
    url: amqp://guest:guest@localhost:5672/
    queue: resource.instance.created
    exchange: resource.events
    routing_key: instance.created
  kubernetes:
    kubeconfig: C:/Users/hp/.kube/config
    # Ingress 域名（HTTP 模式）
    ingress_domain: "demo.localtest.me"
    # ingress-nginx 配置（TCP/UDP 模式）
    ingress_nginx_namespace: "ingress-nginx"
    ingress_nginx_lb_service: "ingress-nginx-controller"
    # TCP/UDP 外部端口范围（通过 ConfigMap 暴露）
    tcp_udp_port_range_start: 30000
    tcp_udp_port_range_end: 32767
